### ISSUE TITLE
[question] How to include components into another component?

### ISSUE THREAD

**Issue by fjaguero** [ryanswapp/react-meteor-template#4]
Hi,

I have been working with React for a while and I'm used to require the component and just use it. How can I use a component inside another component in react-meteor?

Thanks.

**Comment by ryanswapp** [comment]
You can nest components as deep as you'd like. Lets say you have a PostsList component that is the parent component for a list of posts. The PostsList component would look something like:

```
PostsList = React.createClass({

  render() {
    return (
      // Posts
    )
  }
})
```

The way you'd reference this component in another component would be like this:

```
<PostsList />
```

So, if we had a PostItem component that represented an individual post in a list of posts we would use it in our PostsList component like this:

```
PostsList = React.createClass({

  render() {
    return (
      <div>
        // map through posts passed to PostsList component
        // In this example I'm passing the post data that I get from mapping through an array of post objects
        // as the post prop for the PostItem component
        <PostItem post={post} />
     </div>
    )
  }
})
```

Hopefully that makes sense. Let me know if you have other questions.

**Comment by fjaguero** [comment]
Thanks. I know the logic but forgot the easy it was just to add the template with his variable name in other file.
