### ISSUE TITLE
Visibility of initial User-Account used in bootstrap.jsx

### ISSUE THREAD

**Issue by patrickalbrecht** [ryanswapp/react-meteor-template#6]
First of, great Template!

In the file bootstrap.jsx you create an initial user account like this:

```
Meteor.startup(() => {

    if (Meteor.users.find().count() === 0) {
        Accounts.createUser({
            email: "ryancswapp@gmail.com",
            password: "foodbars"
        });
    }

});
```

Since Meteor bundles all files and delivers everything, which is not forbidden using "Meteor.isServer", it is very likely to have initial credentials being published by accident. So it is recommended to wrap the bootstrap-process as the following code shows

```
if (Meteor.isServer) {
    Meteor.startup(() => {

        if (Meteor.users.find().count() === 0) {
            Accounts.createUser({
                email: "ryancswapp@gmail.com",
                password: "foodbars"
            });
        }

    });
}
```

**Comment by ryanswapp** [comment]
Hi!

That startup code is only for development. In an actual application you would use another strategy for adding the first user such as logging into the database shell and manually adding a user. That said, I see no reason why the code couldn't be wrapped in a server block. If you'd like to make a pull request I'd be happy to accept it! :)

**Comment by patrickalbrecht** [comment]
Done ;)
